[package]
name = "pinocchio-escrow"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
pinocchio = "0.9.2"
pinocchio-pubkey = "0.3.0"
pinocchio-system = "0.3.0"
pinocchio-token = "0.4.0"

[lib]
crate-type = ["lib", "cdylib"]
